name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Deploy
        run: |
          mkdir -p docs
          cp -r "TechNinjaCode/WebDev-Challenges/Blog Preview Card/"* docs/
          git config --global user.name "TechNinjaCode"
          git config --global user.email "varmasaurav28@gmail.com"
          git add docs/*
          git commit -m "Deploy to GitHub Pages" || echo "No changes to commit"
          git push origin HEAD:gh-pages
